services: 
  backend: 
      build: 
        context: .
        dockerfile: DockerFile
      image: backend:latest
      container_name: backend
      restart: always
      ports: 
        - 8000:${BACKEND_PORT}

# docker compose build
#    - docker compose build --no-cache
# docker compose up
#    - docker compose up -d